USE [master]
GO

/****** Object:  Database [AtliQ_Hotels]    Script Date: 21-02-2023 20:55:29 ******/
CREATE DATABASE [AtliQ_Hotels]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AtliQ_Hotels', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\AtliQ_Hotels.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AtliQ_Hotels_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\AtliQ_Hotels_log.ldf' , SIZE = 139264KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AtliQ_Hotels].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AtliQ_Hotels] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AtliQ_Hotels] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AtliQ_Hotels] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AtliQ_Hotels] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AtliQ_Hotels] SET ARITHABORT OFF 
GO

ALTER DATABASE [AtliQ_Hotels] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AtliQ_Hotels] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AtliQ_Hotels] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AtliQ_Hotels] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AtliQ_Hotels] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AtliQ_Hotels] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AtliQ_Hotels] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AtliQ_Hotels] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AtliQ_Hotels] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AtliQ_Hotels] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AtliQ_Hotels] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AtliQ_Hotels] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AtliQ_Hotels] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AtliQ_Hotels] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AtliQ_Hotels] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AtliQ_Hotels] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AtliQ_Hotels] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AtliQ_Hotels] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AtliQ_Hotels] SET  MULTI_USER 
GO

ALTER DATABASE [AtliQ_Hotels] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AtliQ_Hotels] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AtliQ_Hotels] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AtliQ_Hotels] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AtliQ_Hotels] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AtliQ_Hotels] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [AtliQ_Hotels] SET QUERY_STORE = ON
GO

ALTER DATABASE [AtliQ_Hotels] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [AtliQ_Hotels] SET  READ_WRITE 
GO


